spring:
  datasource:
    url: jdbc:mysql://localhost:3307/pedido
    username: root
    password: root
    hikari:
      connection-timeout: 2000
      initilization-failt-timeout: 0
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: pedido
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 3
      client-id: pedido
      transaction-id-prefix: ted
  flyway:
    locations:
      - classpath:db/migration

server:
  port: 8888

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


app.topic.create: transacao-crate